### ISSUE TITLE
error in  shorteners.py: class BitlyShortener

### ISSUE THREAD

**Issue by darvinwcc** [ellisonleao/pyshorteners#25]
In shorteners.py: class BitlyShortener
the code is:
if response.ok:
            data = response.json()
            if 'statusCode' in data and data['statusCode'] == 'OK':
                return data['results'][self.url]['shortUrl']
        raise ShorteningErrorException("There was an error shortening this "
                                       "url")

must be because BitlyShortener' object has no attribute 'url':
if response.ok:
            data = response.json()
            if 'statusCode' in data and data['statusCode'] == 'OK':
                return data['results'][url]['shortUrl']
        raise ShorteningErrorException("There was an error shortening this "
                                       "url")

**Comment by ellisonleao** [comment]
Thanks for the report @darvinwcc  . I am working on a 1.0 version now, and those errors should be fixed ASAP
